name: Hello

on:
    push:
        branches: [main]
jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: say hello
              run: echo "Hello Dosto"
    say:
        runs-on: ubuntu-latest
        needs: [greet]
        steps:
            - name: say good morning
              run: echo "Good Morning"